fs: don't fail if AUFS is absent
On Ubuntu Trusty, kernel is compiled with "AUFS=m" but no AUFS module is
available unless linux-image-extra-3.13.* is installed. Since we assume
that if the module is absent, it must be builtin, we continue. However,
when trying for real, we fail. In this case, fallback to not using AUFS.

diff --git a/eudyptula-boot b/eudyptula-boot
--- a/eudyptula-boot
+++ b/eudyptula-boot
@@ -315,7 +315,10 @@ case $$,$STATE in
             if [ -n "$AUFS" ]; then
                 mkdir /tmp/target/rw
                 mount -n -t tmpfs tmpfs     /tmp/target/rw      -o rw
-                mount -n -t aufs  aufs      /tmp/target/overlay -o noxino,noatime,dirs=/tmp/target/rw:/tmp/target/ro=ro
+                mount -n -t aufs  aufs      /tmp/target/overlay -o noxino,noatime,dirs=/tmp/target/rw:/tmp/target/ro=ro 2> /dev/null || {
+                    log_warn_msg "Unable to use AUFS"
+                    mount -n --bind /tmp/target/ro /tmp/target/overlay
+                }
             else
                 mount -n --bind /tmp/target/ro /tmp/target/overlay
             fi
